### ISSUE TITLE
Types for TypeScript

### ISSUE THREAD

**Issue by JasonEtco** [gr2m/before-after-hook#47]
Happy Holidays ❤️ I'm using this wonderful library (finally) in a TypeScript project, which required me to write some types for the lib. From reading the code (and the excellent docs ✨), here's what I came up with:

```typescript
declare module 'before-after-hook' {
  export type HookType = {
    new (): any
    (name: string, data: any, method: (...any) => any): Promise<any>
    before (name: string, method: (...any) => any): Promise<any>
    error (name: string, method: (...any) => any): Promise<any>
    after (name: string, method: (...any) => any): Promise<any>
    wrap (name: string, method: (...any) => any): Promise<any>
    remove (name: string, beforeHookMethod: (...any) => any): Promise<any>
  }

  const Hook: HookType
  export default Hook
}
```

If you're interested, I can open a PR here adding an `index.d.ts` file and the `types` field to the `package.json` - or, I can get this added into [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), the large store of types for libraries. Let me know what you think!

**Comment by gr2m** [comment]
Sure!
