### ISSUE TITLE
hook() not passing options to method

### ISSUE THREAD

**Issue by dcustodio** [gr2m/before-after-hook#50]
I upgraded the library from 1.1.0 to 1.3.1 and since then it behaved differently.

the code is as follows:

`        
return hook('ask', askPayload, (askOptions) => {
            emit('ask', askOptions)
        })
`

from version 1.3.1 the askOptions is `undefined`

**Comment by gr2m** [comment]
Could you please make an example on http://runkit.com/ reproducing the problem? You can require different versions of the same package in the same code snippet, e.g. see https://runkit.com/gr2m/octokit-rest-js-1141 as an example

**Comment by dcustodio** [comment]
Hi, here it is:
https://runkit.com/dcustodio/before-after-hooks-issue

thanks!

**Comment by gr2m** [comment]
Thank you, I’m looking into it

**Comment by gr2m** [comment]
I’ve made a simpler notebook which loads both versions and confirms the regression you run into:
https://runkit.com/gr2m/5c34f5b6a1b4e100115c8361

Thanks for reporting it! 

Next step will be to create a pull request with a failing tests reproducing it. Would you like to give that a try? I’m occupied with other work right now I’m afraid but I’m happy to help you out if you get stuck
