### ISSUE TITLE
Question: actually supports chaining? 

### ISSUE THREAD

**Issue by MunifTanjim** [gr2m/before-after-hook#61]
`README.md` mentions these:

> Add before hook for given name. Returns hookCollection instance for chaining.

> Add error hook for given name. Returns hookCollection instance for chaining.

> Add after hook for given name. Returns hook instance for chaining.

> Add wrap hook for given name. Returns hookCollection instance for chaining.

> Removes hook for given name. Returns hookCollection instance for chaining.

The current [typescript types](https://github.com/gr2m/before-after-hook/blob/4f55cbe3c10c47f6dc13d4b306ed9e2a342279b9/index.d.ts) also reflects this.

That means something like this is possible:

```js
hooks.before('name', beforeHook).after('name', afterHook)
```

But does it actually supports chaining?

Or is it just wrong documentation?

**Comment by gr2m** [comment]
It should, but it looks like it doesn’t. Nobody complained about it so far, so I think we can just remove the `Returns ... for chaining` from the docs.

Great work uncovering this 👍
